namespace Gremlins.Services;

/// <summary>
/// Every theme the UI knows about. <see cref="AppThemePreference.System"/> follows Windows light/dark apps;
/// <see cref="AppThemePreference.Dark"/> / <see cref="AppThemePreference.Light"/> are the classic Gremlins pair;
/// the rest are bonus chaos (including 64 evenly spaced hues on the prismatic ring).
/// </summary>
public enum AppThemePreference
{
    System,

    Dark,
    Light,

    /* --- Fan-favorites & editor lore --- */
    Dracula,
    Nord,
    GruvboxDark,
    GruvboxLight,
    SolarizedDark,
    SolarizedLight,
    TokyoNight,
    CatppuccinMocha,
    CatppuccinLatte,
    OneDark,
    Monokai,
    RosePine,
    Everforest,
    AyuMirage,
    NightOwl,
    ShadesOfPurple,
    Synthwave84,
    MatrixGreen,
    AmberCRT,
    HotDogStand,
    VaporwavePastel,
    PaperWhite,
    GlitchCore,
    UnicornAcid,
    BeigeNightmare,
    MiamiVice,
    CorpBland,
    ZombieMold,
    Steampunk,
    ClippyAssist,

    /* --- Prismatic ring (64 stops around the hue wheel) --- */
    Prismatic01,
    Prismatic02,
    Prismatic03,
    Prismatic04,
    Prismatic05,
    Prismatic06,
    Prismatic07,
    Prismatic08,
    Prismatic09,
    Prismatic10,
    Prismatic11,
    Prismatic12,
    Prismatic13,
    Prismatic14,
    Prismatic15,
    Prismatic16,
    Prismatic17,
    Prismatic18,
    Prismatic19,
    Prismatic20,
    Prismatic21,
    Prismatic22,
    Prismatic23,
    Prismatic24,
    Prismatic25,
    Prismatic26,
    Prismatic27,
    Prismatic28,
    Prismatic29,
    Prismatic30,
    Prismatic31,
    Prismatic32,
    Prismatic33,
    Prismatic34,
    Prismatic35,
    Prismatic36,
    Prismatic37,
    Prismatic38,
    Prismatic39,
    Prismatic40,
    Prismatic41,
    Prismatic42,
    Prismatic43,
    Prismatic44,
    Prismatic45,
    Prismatic46,
    Prismatic47,
    Prismatic48,
    Prismatic49,
    Prismatic50,
    Prismatic51,
    Prismatic52,
    Prismatic53,
    Prismatic54,
    Prismatic55,
    Prismatic56,
    Prismatic57,
    Prismatic58,
    Prismatic59,
    Prismatic60,
    Prismatic61,
    Prismatic62,
    Prismatic63,
    Prismatic64,
}
