namespace Gremlins.Services.Themes;

/// <summary>All brush tokens used by app styles and main window chrome.</summary>
public readonly record struct ThemeColors(
    string BgDeep,
    string BgCard,
    string CardHover,
    string AccentGreen,
    string AccentGreenDim,
    string AccentRed,
    string TextPrimary,
    string TextMuted,
    string Border,
    string WindowBg,
    string BorderOuter,
    string TitleBar,
    string TitleAccent,
    string FooterBg,
    string CloseButtonFg,
    string ComboDropBg,
    string ComboDropBorder,
    string ComboItemHover,
    string ComboItemSelected,
    string ComboMultiHighlight,
    string ComboChromeBg,
    string ComboHoverBorder,
    string ColorPrimaryGlow,
    string ActionPrimaryBg,
    string ActionPrimaryBgHover,
    string ActionPrimaryBgPressed,
    string ActionSecondaryBg,
    string ActionSecondaryHover,
    string ActionSecondaryBorderHover,
    string ActionSecondaryPressed);
